# -*- coding: utf-8 -*-
"""suc_translate_ai_ollama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2S8oB1puDxFJTyDMlEju0I1ldtyM8TN
"""







!git clone https://github.com/mrseanryan/gpt-summarizer.git

!curl -fsSL https://ollama.com/install.sh | sh

!ollama run llama3.1:8b

!ollama list

!ollama run llama3.1:8b

print('Checking available Ollama models:')
!ollama list

!ollama pull phi3

!ollama run phi3:latest

print('Checking available Ollama models:')
!ollama list

print('Checking available Ollama models:')
!ollama list

!ollama run phi3:latest

!pip install cornsnake~=0.0.60 html2text==2024.2.26 json5==0.9.25 ollama==0.2.0 PyMuPDF==1.24.1 pyyaml==6.0.1 ruff==0.3.5

!pip3 install --upgrade ctransformers pymupdf

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gpt-summarizer
!./go.sh

!poetry run python -m gpt_summarizer.main_cli

!python /content/gpt-summarizer/gpt_summarizer/main_cli.py --help

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gpt-summarizer/gpt_summarizer

!python main_cli.py -h

# إنشاء ملف نصي تجريبي يحتوي على نص طويل (يمكنك تعديل النص)
sample_text = """
Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence displayed by animals including humans.
AI research has been defined as the field of study of intelligent agents, which refers to any system that perceives its environment and takes actions that maximize its chance of achieving its goals.
The term "artificial intelligence" had previously been used to describe machines that mimic and display "human" cognitive skills that are associated with the human mind, such as "learning" and "problem-solving".
This definition has since been rejected by major AI researchers who now describe AI in terms of rationality and acting rationally, which does not limit how intelligence can be articulated.
"""

with open("text.txt", "w") as f:
    f.write(sample_text)

print("تم إنشاء ملف text.txt بنجاح")

!python -m gpt_summarizer --input_file text.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd gpt-summarizer

import ollama

# قراءة الملف النصي
with open("text.txt", "r") as f:
    text_content = f.read()

# إرسال النص إلى Llama 3.1 للتلخيص
response = ollama.chat(model='llama3.1:8b', messages=[
  {
    'role': 'user',
    'content': f"Summarize this text: {text_content}",
  },
])

print("--- الملخص من Llama 3.1 ---")
print(response['message']['content'])

import ollama

# قراءة الملف النصي
with open("text.txt", "r") as f:
    text_content = f.read()

# إرسال النص إلى Llama 3.1 للتلخيص
response = ollama.chat(model='llama3.1:8b', messages=[
  {
    'role': 'user',
    'content': f"لخص هذا النص باللغة العربية: {text_content}",
  },
])

print("--- الملخص من Llama 3.1 ---")
print(response['message']['content'])

import ollama

# قراءة الملف النصي
with open("text.txt", "r") as f:
    text_content = f.read()

# إرسال النص إلى Llama 3.1 للتلخيص
response = ollama.chat(model='llama3.1:8b', messages=[
  {
    'role': 'user',
    'content': f"ترجم هذا النص الى اللغة العربية: {text_content}",
  },
])

print("--- الملخص من Llama 3.1 ---")
print(response['message']['content'])

"""--- الملخص من Llama 3.1 ---
الهندسة الجديدة (الذكاء الاصطناعي) هي الذكاء الذي يظهر في الآلات، وليس الذكاء الطبيعي المُظهَر في الحيوانات بما في ذلك الإنسان. وقد تم تعريف البحث عن الذكاء الاصطناعي على أنه مجال دراسة
"""

اكتب هذا (للحصول على ملخص عربي):
code Python


'content': f"لخص هذا النص باللغة العربية: {text_content}",



أو إذا أردته كنقاط محددة:
code Python


'content': f"Give me a summary of this text as bullet points: {text_content}",

# Commented out IPython magic to ensure Python compatibility.
# 1. ادخل إلى المجلد الرئيسي أولاً
# %cd /content/gpt-summarizer

# 2. شغل الأمر واستدعي الموديول (لاحظ النقطة والشرطة السفلية)
!python3 -m gpt_summarizer.main_cli text.txt --engine ollama --model llama3.1:8b







import ollama

# قراءة النص
with open("text.txt", "r") as f:
    text_content = f.read()

# إرسال النص مع تعليمات دقيقة (System Prompt)
response = ollama.chat(model='llama3.1:8b', messages=[
  {
    'role': 'system',
    'content': 'أنت خبير لغوي ومحلل نصوص. قم بتلخيص النص التالي باللغة العربية الفصحى السليمة، وركز على استخراج الأفكار الرئيسية بأسلوب مترابط وليس ترجمة حرفية.'
  },
  {
    'role': 'user',
    'content': text_content,
  },
])

print("--- الملخص المحسن ---")
print(response['message']['content'])

import ollama
import os

# --- إعدادات ---
input_file = "text.txt"           # اسم الملف الأصلي
output_file = "translated_text.txt" # اسم ملف الترجمة
chunk_size = 2000                 # عدد الأحرف في كل دفعة (حوالي 300-400 كلمة)
model_name = "llama3.1:8b"        # الموديل المستخدم

# 1. دالة لتقسيم النص إلى أجزاء
def split_text(text, size):
    # نقسم النص بحيث لا نقطع الكلمات (نحاول التقسيم عند المسافات)
    chunks = []
    while len(text) > size:
        # نجد آخر مسافة قبل الحد الأقصى
        split_index = text.rfind(' ', 0, size)
        if split_index == -1: # إذا لم توجد مسافة (كلمة طويلة جداً)
            split_index = size

        chunks.append(text[:split_index])
        text = text[split_index:]
    chunks.append(text)
    return chunks

# 2. قراءة الملف الطويل
if not os.path.exists(input_file):
    print(f"Error: File {input_file} not found!")
else:
    with open(input_file, "r", encoding="utf-8") as f:
        full_text = f.read()

    # تقسيم النص
    text_chunks = split_text(full_text, chunk_size)
    print(f"تم تقسيم الملف إلى {len(text_chunks)} جزء للترجمة...")

    # تنظيف ملف المخرجات القديم إن وجد
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("")

    # 3. البدء في الترجمة (جزء بجزء)
    for i, chunk in enumerate(text_chunks):
        print(f"جاري ترجمة الجزء {i+1} من {len(text_chunks)}...")

        try:
            response = ollama.chat(model=model_name, messages=[
                {
                    'role': 'system',
                    'content': 'أنت مترجم محترف. قم بترجمة النص التالي إلى اللغة العربية بدقة وأسلوب أدبي متماسك. لا تضف أي مقدمات أو شروحات، فقط أعطني الترجمة.'
                },
                {
                    'role': 'user',
                    'content': chunk
                },
            ])

            translated_chunk = response['message']['content']

            # حفظ الترجمة مباشرة في الملف (append)
            with open(output_file, "a", encoding="utf-8") as f:
                f.write(translated_chunk + "\n\n")

        except Exception as e:
            print(f"حدث خطأ في الجزء {i+1}: {e}")

    print(f"\n✅ تمت الترجمة بنجاح! الملف المحفوظ: {output_file}")

    # عرض أول جزء من الترجمة للتأكد
    print("\n--- مقتطف من الترجمة ---")
    with open(output_file, "r", encoding="utf-8") as f:
        print(f.read()[:500] + "...")

# داخل حلقة الـ loop
        response = ollama.chat(
            model=model_name,
            messages=[
                {
                    'role': 'system',
                    'content': 'أنت مترجم تقني محترف. قم بترجمة النص إلى العربية بأسلوب علمي رصين. انتبه للمصطلحات التقنية (مثلاً: Agents = وكلاء ذكية، Learning = التعلم، Problem-solving = حل المشكلات). تجنب الترجمة الحرفية واكتب بلغة عربية سليمة نحوياً.'
                },
                {
                    'role': 'user',
                    'content': chunk
                },
            ],
            # إضافة خيارات لتقليل العشوائية ومنع الهلوسة
            options={
                'temperature': 0.1,  # تقليل الحرارة لزيادة الدقة
                'top_p': 0.9
            }
        )

import ollama
import os
import time
from tqdm.notebook import tqdm  # شريط تقدم لبيئة كولاب

# ------------------- إعدادات المستخدم -------------------
INPUT_FILE = "text.txt"           # اسم الملف الذي تريد ترجمته
OUTPUT_FILE = "translated_text.txt" # اسم الملف الناتج
MODEL_NAME = "llama3.1:8b"        # الموديل المستخدم
CHUNK_SIZE = 1500                 # حجم الجزء (تم تقليله قليلاً لضمان جودة أعلى)
# --------------------------------------------------------

def split_text_smart(text, max_length):
    """
    تقسيم النص بذكاء عند المسافات أو علامات الترقيم لعدم قطع الجمل.
    """
    chunks = []
    while len(text) > max_length:
        # البحث عن أقرب نقطة أو مسافة قبل الحد الأقصى
        # نحاول البحث عن نهاية جملة (.) أولاً ليكون التقسيم منطقياً
        split_index = text.rfind('.', 0, max_length)

        if split_index == -1: # إذا لم نجد نقطة، نبحث عن مسافة
            split_index = text.rfind(' ', 0, max_length)

        if split_index == -1: # إذا كانت جملة عملاقة جداً، نقطع عند الحد الأقصى
            split_index = max_length

        # إضافة الجزء للقائمة (مع احتساب النقطة في الجزء الأول)
        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    """
    دالة لترجمة جزء واحد مع محاولة إعادة المحاولة عند الفشل
    """
    system_prompt = (
        "أنت مترجم تقني وأكاديمي محترف. "
        "مهمتك: ترجمة النص التالي من الإنجليزية إلى العربية الفصحى السليمة. "
        "القواعد: "
        "1. استخدم مصطلحات علمية دقيقة (مثلاً: Agents = وكلاء، AI = الذكاء الاصطناعي). "
        "2. حافظ على قواعد النحو (تذكير وتأنيث الأفعال بدقة). "
        "3. لا تضف أي حوار جانبي، أعطني الترجمة فقط."
    )

    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.1,  # دقة عالية جداً ومنع الهلوسة
                    'top_p': 0.9,
                }
            )
            return response['message']['content']
        except Exception as e:
            print(f"\n⚠️ تحذير: فشلت المحاولة {attempt+1} لترجمة الجزء. الخطأ: {e}")
            time.sleep(2) # انتظار ثانيتين قبل المحاولة مرة أخرى

    return "[فشلت ترجمة هذا الجزء بعد عدة محاولات]"

# ------------------- التنفيذ الرئيسي -------------------

# 1. التأكد من وجود الملف
if not os.path.exists(INPUT_FILE):
    print(f"❌ خطأ: الملف {INPUT_FILE} غير موجود! تأكد من رفع الملف وتسميته بشكل صحيح.")
else:
    print("🚀 جاري قراءة الملف وتقسيمه...")
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    # تقسيم النص
    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"📄 تم تقسيم النص إلى {len(chunks)} جزء. البدء في الترجمة...\n")

    # مسح محتوى ملف المخرجات القديم لبدء كتابة جديدة
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    # 2. حلقة الترجمة مع شريط التقدم
    # نستخدم tqdm لعرض شريط التحميل
    for i, chunk in enumerate(tqdm(chunks, desc="جاري الترجمة")):

        translated_text = translate_segment(chunk)

        # كتابة النتيجة فوراً للملف (حتى لا يضيع شيء لو انقطع الاتصال)
        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(translated_text + "\n\n")

    print(f"\n✅ تمت العملية بنجاح! تم حفظ الترجمة في: {OUTPUT_FILE}")

    # عرض عينة
    print("-" * 30)
    print("👀 عينة من بداية الترجمة:")
    with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
        print(f.read()[:500] + "...")
    print("-" * 30)

import ollama
import os
import time
from tqdm.notebook import tqdm # Colab Progress Bar

# ------------------- User Settings -------------------
INPUT_FILE = "text.txt" # Name of the file you want to translate
OUTPUT_FILE = "translated_text.txt" # Name of the output file
MODEL_NAME = "llama3.1:8b" # Model used
CHUNK_SIZE = 1500 # Chunk size (slightly reduced for better quality)
# --------------------------------------------------------

def split_text_smart(text, max_length):

""
Smartly splits text at spaces or punctuation marks to avoid breaking sentences.

""
chunks = []

while len(text) > max_length:

# Finds the nearest point or space before the maximum

# Attempts to find the end of a sentence (.) first for logical splitting
split_index = text.rfind('.', 0, max_length)

if split_index == -1: # If we don't find a point, we look for a distance

split_index = text.rfind(' ', 0, max_length)

if split_index == -1: # If the sentence is too long, we cut at the maximum length

split_index = max_length

# Add the segment to the list (counting the point in the first segment)

chunks.append(text[:split_index + 1])

text = text[split_index + 1:].strip()

if text:

chunks.append(text)

return chunks

def translate_segment(text_chunk, retries=3):

""

A function to translate one segment and attempt to retry if it fails

""
system_prompt = (
"You are a professional technical and academic translator."

"Your task: Translate the following text from English into Modern Standard Arabic."
Rules:

1. Use precise scientific terminology (e.g., Agents = Agents, AI = Artificial Intelligence).

2. Maintain grammatical rules (precise gender agreement of verbs).

3. Do not add any side dialogue; just provide the translation.

)

for attempt in range(retries):

try:

response = ollama.chat(
model=MODEL_NAME,

messages=[
{'role': 'system', 'content': system_prompt},

{'role': 'user', 'content': text_chunk},

],

options={
'temperature': 0.1, # Very high accuracy and hallucination prevention

'top_p': 0.9,

}
)

return response['message']['content']

except Exception as e:

print(f"\n⚠️ Warning: The attempt to translate the part failed. Error: {e}")

time.sleep(2) # Wait two seconds before trying again

return "[This part failed to translate after several attempts]"

# ------------------- Main Implementation -------------------

# 1. Check if the file exists
if not os.path.exists(INPUT_FILE):

print(f"❌ Error: The file {INPUT_FILE} does not exist! Make sure you uploaded and named the file correctly.")
else:

print("🚀 Reading and splitting the file...")

with open(INPUT_FILE, "r", encoding="utf-8") as f:

full_text = f.read()

# Split the text

chunks = split_text_smart(full_text, CHUNK_SIZE)

print(f"📄 The text has been split into {len(chunks)} chunks. Starting to translate...")

# Clear the contents of the old output file to start writing a new one
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:

f.write("")

# 2. Translation Loop with Progress Bar

# We use tqdm to display the progress bar

for i, chunk in enumerate(tqdm(chunks, desc="Translating in progress")):

translated_text = translate_segment(chunk)

# Write the result immediately to the file (so nothing is lost if the connection is interrupted)

with open(OUTPUT_FILE, "a", encoding="utf-8") as f:

f.write(translated_text + "\n\n")

print(f"\n✅ Operation completed successfully! Translation saved in: {OUTPUT_FILE}")

# Display Sample

print("-" * 30)

print("👀 Sample from the beginning of the translation:")

with open(OUTPUT_FILE, "r", encoding="utf-8") as f:

print(f.read()[:500] + "...")

print("-" * 30)

import ollama
import os
import time
from tqdm.notebook import tqdm  # Progress bar for Colab

# ------------------- Configuration -------------------
INPUT_FILE = "/content/gpt-summarizer/gpt_summarizer/text.txt"           # Source file name
OUTPUT_FILE = "translated_text.txt" # Output file name
MODEL_NAME = "llama3.1:8b"        # Model to use
CHUNK_SIZE = 1500                 # Character limit per chunk
# -----------------------------------------------------

def split_text_smart(text, max_length):
    """
    Splits text intelligently at periods (.) or spaces to avoid cutting sentences in half.
    """
    chunks = []
    while len(text) > max_length:
        # Find the last period before the max length to keep sentences intact
        split_index = text.rfind('.', 0, max_length)

        # If no period is found, look for the last space
        if split_index == -1:
            split_index = text.rfind(' ', 0, max_length)

        # If the chunk is one giant string (no spaces), cut at max_length
        if split_index == -1:
            split_index = max_length

        # Append the chunk including the punctuation
        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    """
    Translates a single text chunk with retry logic in case of failure.
    """
    # The system prompt is in English, but instructs the AI to output Arabic.
    system_prompt = (
        "You are an expert technical and academic translator. "
        "Your task is to translate the following English text into professional, high-quality Arabic. "
        "Guidelines: "
        "1. Use accurate technical terms (e.g., translate 'Agents' correctly in an AI context). "
        "2. Ensure perfect Arabic grammar. "
        "3. Output ONLY the translation, without any introductory or concluding remarks."
    )

    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.1,  # Low temperature for high accuracy/low hallucination
                    'top_p': 0.9,
                }
            )
            return response['message']['content']
        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Error: {e}")
            time.sleep(2) # Wait 2 seconds before retrying

    return "[Failed to translate this segment after multiple attempts]"

# ------------------- Main Execution -------------------

def main():
    # 1. Check if input file exists
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found! Please upload it first.")
        return

    print("--- Starting Process ---")
    print(f"Reading file: {INPUT_FILE}...")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    # 2. Split text into chunks
    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts. Starting translation...\n")

    # Clear previous output file content
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    # 3. Process chunks with a progress bar
    for chunk in tqdm(chunks, desc="Translating"):

        translated_text = translate_segment(chunk)

        # Append result immediately to file (safeguard against crashes)
        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(translated_text + "\n\n")

    print(f"\n[Success] Translation complete!")
    print(f"Output saved to: {OUTPUT_FILE}")

    # 4. Show a sample
    print("-" * 30)
    print("Sample of the output:")
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()

"""--- Starting Process ---
Reading file: /content/gpt-summarizer/gpt_summarizer/text.txt...
Document split into 1 parts. Starting translation...

Translating: 100%
 1/1 [04:48<00:00, 288.13s/it]


[Success] Translation complete!
Output saved to: translated_text.txt
## ------------------------------
Sample of the output:
التعلم الإلكتروني (AI) هو الذكاء الذي يظهره الآلات، على عكس الذكاء الطبيعي الذي يتم.displayed من قبل الحيوانات بما في ذلك البشر.

تم تعريف البحث عن التعلم الإلكتروني على أنه مجال دراسة एजنسيات ذكية، والتي تشير إلى أي نظام يمكنه أن يدرك بيئته ويتخذ إجراءات تزيد فرص تحقيق أهدافه.
استخدم المصطلح "التعلم الإلكتروني" سابقًا لوصف الآلات التي تماثل وتظهر مهارات المعرفية البشرية، مثل "تعلم" و " حل المشكلات".
تم رفض هذا التعريف منذ ذلك الحين من قبل باحثي AI الكبار الذين يصفون الآن التعلم الإلكتروني بال م...
# ------------------
"""

import ollama
import os
import time
from tqdm.notebook import tqdm  # Progress bar

# ------------------- Configuration -------------------
INPUT_FILE = "text.txt"
OUTPUT_FILE = "translated_text.txt"
MODEL_NAME = "llama3.1:8b"
CHUNK_SIZE = 1000                 # Reduced chunk size for better focus
# -----------------------------------------------------

def split_text_smart(text, max_length):
    """
    Splits text intelligently at periods or newlines.
    """
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind('.', 0, max_length)
        if split_index == -1:
            split_index = text.rfind('\n', 0, max_length)
        if split_index == -1:
            split_index = text.rfind(' ', 0, max_length)
        if split_index == -1:
            split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    """
    Translates text with strict enforcement of Arabic terminology.
    """

    # STRICT SYSTEM PROMPT
    # We explicitly map the terms that were failing (AI -> الذكاء الاصطناعي)
    # We explicitly forbid non-Arabic characters.
    system_prompt = (
        "You are a professional translator. Translate the text from English to Arabic. \n"
        "STRICT RULES:\n"
        "1. Terminology: Translate 'Artificial Intelligence' strictly as 'الذكاء الاصطناعي'. NEVER translate it as 'E-learning'.\n"
        "2. Terminology: Translate 'Agents' as 'وكلاء' or 'أنظمة'.\n"
        "3. Output Language: The output must be 100% Arabic. Do NOT use English words (like 'displayed').\n"
        "4. Character Set: Do NOT use Hindi or Urdu characters (like 'ए'). Use only standard Arabic letters.\n"
        "5. Grammar: Use formal, correct Arabic grammar."
    )

    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.1,  # Keep it deterministic
                    'top_p': 0.85,       # Slightly stricter sampling
                    'num_predict': 512,  # Ensure enough space for output
                }
            )
            return response['message']['content']
        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Error: {e}")
            time.sleep(2)

    return "[Translation Failed]"

# ------------------- Main Execution -------------------

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found.")
        return

    print("--- Starting Process (Strict Mode) ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    # Reset output file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        translated_text = translate_segment(chunk)

        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(translated_text + "\n\n")

    print(f"\n[Success] Translation complete!")

    # Show sample
    print("-" * 30)
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()

"""عودة f'''SYSTEM: أنت محلل نصوص مفيد يعرف كيفية تلخيص النص إلى صحيح {get_output_format_name()}.
المستخدم: تلخيص هذا النص المشار إليه بالخلفيات:
"""



"""### https://github.com/mrseanryan/gpt-summarizer/blob/9dd9ae6bf70de990294a14d28d027821e5e530f1/gpt_summarizer/prompts.py#L5

# yaml أرخص لتوليد
OUTPUT_FORMAT_YAML = '''
يجب أن يكون تنسيق الإخراج صالحًا YAML ، مع الحقول: title_in_quotes ، short_summary ، long_summary ، الفقرات.
- لا تقم بتضمين أحرف YAML الخاصة في النص (على سبيل المثال: اقتباسات مفردة أو قولون)
- لا تستخدم مشغل استمرار الخط '|'
- للرصاص استخدام الواصلة '-'، لا تستخدم '*'
- دلالة على الناتج الإجمالي مع "" لا "--"
'''

OUTPUT_FORMAT_YAML_SHORTER = '''
The output format must be valid YAML, with the fields: title_in_quotes, short_summary, long_summary.
- do NOT include YAML special characters in the text (for example: single quotes or colons)
- do NOT use the line-continuation operator '|'
- for bullets use hyphen '-', do NOT use '*'
- denote the overall output with ``` NOT '---'
'''

OUTPUT_TEXT_STYLE = "The output text preserve the original style and tone. The summary MUST summarize the contents of the text, this is NOT a commentary."

SYSTEM_PROMPT__OPENAI = f"You are a summary assistant, skilled in summarizing texts whilst preserving the main points and original style. The target language is {config.TARGET_LANGUAGE}."

OUTPUT_TEXT_STYLE = "نص الإخراج يحافظ على النمط الأصلي والنغمة. يجب أن يلخص الملخص محتويات النص، هذا ليس تعليقا".

SYSTEM_PROMPT__OPENAI = f"You مساعد ملخص، ماهر في تلخيص النصوص مع الحفاظ على النقاط الرئيسية والأسلوب الأصلي. اللغة المستهدفة هي {config.TARGET_LANGUAGE}.

PARAGRAPHS = "\n    - paragraphs should be an array of one sentence summaries: one sentence for each paragraph.\n"

    return f'''

return f'''
1. Analyze the given input text.
    - The input text is delimited by triple backticks.
2. {_get_output_format(include_paragraphs=include_paragraphs)}
3. Create a title and a short and long summary in the target language {target_language}.
    - {OUTPUT_TEXT_STYLE}
    - short_summary should be {config.SHORT_SUMMARY_WORD_COUNT} words long.
    - long_summary should be {config.LONG_SUMMARY_WORD_COUNT} words long.{PARAGRAPHS}
4. After generating the summaries, stop and check that the output is valid {get_output_format_name()}.

العودة f '''
1. تحليل نص الإدخال المعطى.
    - يتم تعيين نص الإدخال بواسطة خلفيات ثلاثية.
2. {_get_output_format(include_paragraphs=include_paragraphs)}
3. إنشاء عنوان وملخص قصير وطويل في اللغة الهدف {target_language}.
    - {OUTPUT_TEXT_STYLE}
    - يجب أن يكون {config.SHORT_SUMMARY_WORD_COUNT} كلمات طويلة.
    - يجب أن يكون {config.LONG_SUMMARY_WORD_COUNT} كلمات طويلة.{ الفقرات}
4. بعد إنشاء الملخصات ، توقف وتحقق من أن الإخراج صالح {get_output_format_name()}.
"""



"""        PARAGRAPHS = "\n        - paragraphs should be an array of one sentence shortened-versions: one sentence for each paragraph.\n"

    print("[complex prompt]")
    return f'''Examine the provided user prompt, the text input, noting its style of writing and tone.

RULES:
R1. Do NOT mention the text, study, document or paper.
R2. Create shorted versions of the original text, in the same style.
R3. Preserve the 'person' or 'narrator' of the text: for example, if the text is written in first-person, then also output in first-person.

PROCESS TO FOLLOW:
    1. Analyze the given input text, noting its style and tone.
        - The input text is delimited by triple backticks.
    2. {_get_output_format(include_paragraphs=include_paragraphs)}
    3. Create a title and a short and long version in the target language {target_language}.
        - {OUTPUT_TEXT_STYLE}
        - short_summary should be {config.SHORT_SUMMARY_WORD_COUNT} words long, in the original style.
        - long_summary should be {config.LONG_SUMMARY_WORD_COUNT} words long, in the original style.{PARAGRAPHS}
        - shortened texts should be as if excerpts of the original text. example: 'While recent language models have the ability to take long contexts as input, relatively little is known about how well the language models
use longer context.' -> 'Whilst recent language models can accept long contexts, little is know about the quality of output'.
    4. Do NOT output a commentary - do NOT use phrases such as 'The paper examines...', 'It is noted...' or 'This text'.
    5. After generating the shortened texts, stop and check that the output is valid {get_output_format_name()}.

<thinking>
For each generated shortened text:
- check does the generated text follow the RULES.
- check is the writing style and tone same as original.
- check is the shortened text as if part of the original text NOT a commentary.
- check the shortened text is direct, as a primary source, and not a commentary.
- do NOT mention the text, study, document or paper.
- do NOT output a commentary - do NOT use phrases such as 'The paper examines...', 'It is noted...' or 'The text discusses...' or 'This text lists...' or 'The text...' or 'The study...'.
- avoid duplication
[Continue for all items]
</thinking>

text: ```{input_text}```

"""

import ollama
import os
import time
from tqdm.notebook import tqdm  # Progress bar

# ------------------- Configuration -------------------
INPUT_FILE = "/content/gpt-summarizer/gpt_summarizer/text.txt"
OUTPUT_FILE = "translated_text.txt"
MODEL_NAME = "llama3.1:8b"
CHUNK_SIZE = 1000                 # Reduced chunk size for better focus
# -----------------------------------------------------

def split_text_smart(text, max_length):
    """
    Splits text intelligently at periods or newlines.
    """
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind('.', 0, max_length)
        if split_index == -1:
            split_index = text.rfind('\n', 0, max_length)
        if split_index == -1:
            split_index = text.rfind(' ', 0, max_length)
        if split_index == -1:
            split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    """
    Translates text with strict enforcement of Arabic terminology.
    """

    # STRICT SYSTEM PROMPT
    # We explicitly map the terms that were failing (AI -> الذكاء الاصطناعي)
    # We explicitly forbid non-Arabic characters.
    system_prompt = (
        "You are a professional translator. Translate the text from English to Arabic. \n"
        "STRICT RULES:\n"
        "1. Terminology: Translate 'Artificial Intelligence' strictly as 'الذكاء الاصطناعي'. NEVER translate it as 'E-learning'.\n"
        "2. Terminology: Translate 'Agents' as 'وكلاء' or 'أنظمة'.\n"
        "3. Output Language: The output must be 100% Arabic. Do NOT use English words (like 'displayed').\n"
        "4. Character Set: Do NOT use Hindi or Urdu characters (like 'ए'). Use only standard Arabic letters.\n"
        "5. Grammar: Use formal, correct Arabic grammar."
    )

    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.1,  # Keep it deterministic
                    'top_p': 0.85,       # Slightly stricter sampling
                    'num_predict': 512,  # Ensure enough space for output
                }
            )
            return response['message']['content']
        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Error: {e}")
            time.sleep(2)

    return "[Translation Failed]"

# ------------------- Main Execution -------------------

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found.")
        return

    print("--- Starting Process (Strict Mode) ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    # Reset output file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        translated_text = translate_segment(chunk)

        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(translated_text + "\n\n")

    print(f"\n[Success] Translation complete!")

    # Show sample
    print("-" * 30)
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()

"""--- Starting Process (Strict Mode) ---
Document split into 1 parts.

Translating: 100%
 1/1 [05:26<00:00, 326.45s/it]


[Success] Translation complete!
------------------------------
الذكاء الاصطناعي هو الذكاء الذي يظهره الآلات، على عكس الذكاء الطبيعي الذي يتم.displaying بواسطة الحيوانات بما في ذلك البشر.

وقد تم تعريف البحث عن الذكاء الاصطناعي كمجال دراسة الوكلاء الذكيين، والذي يشير إلى أي نظام يمكنه أن يدرك بيئته ويتخذ إجراءات تزيد من فرص تحقيق أهدافه.
تم استخدام مصطلح "الذكاء الاصطناعي" سابقًا لوصف الآلات التي تمثل وتظهر مهارات المعرفية البشرية، مثل "التعلم" وال " حل المشكلات".
وقد تم رفض هذا التعريف منذ ذلك الحين من قبل باحثي الذكاء الاصطناعي الأبرز الذين يصفون الآن الذك...
------------------------------
### New Section
"""



import ollama
import os
import time
from tqdm.notebook import tqdm

# ------------------- Configuration -------------------
INPUT_FILE = "/content/gpt-summarizer/gpt_summarizer/text.txt"
OUTPUT_FILE = "output_arabic.txt"
MODEL_NAME = "llama3.1:8b"
CHUNK_SIZE = 1200  # Good balance for Llama 3 context

# ------------------- PROMPT ENGINEERING -------------------
# Inspired by: mrseanryan/gpt-summarizer/prompts.py
# We define "Personas" to guide the model strictly.

PROMPT_TEMPLATES = {
    "tech_translation": (
        "ROLE: You are an expert Technical Writer and Linguist.\n"
        "TASK: Translate the following English text into professional Arabic.\n"
        "GUIDELINES:\n"
        "1. Accuracy: Preserve technical meaning. Do not dumb it down.\n"
        "2. Terminology: Use standard Arabic technical terms (e.g., 'Artificial Intelligence' -> 'الذكاء الاصطناعي').\n"
        "3. Tone: Formal, objective, and concise. No marketing fluff.\n"
        "4. STRICT OUTPUT: Output ONLY the Arabic translation. No English words. No Hindi characters.\n"
        "5. Formatting: Maintain the original paragraph structure."
    ),
    "tech_summary": (
        "ROLE: You are an expert Technical Writer.\n"
        "TASK: Summarize the key points of the following text in Arabic.\n"
        "GUIDELINES:\n"
        "1. Format: Use bullet points (-).\n"
        "2. Focus: Extract the most important technical facts and arguments.\n"
        "3. Brevity: Be concise but comprehensive.\n"
        "4. Language: The output must be 100% in Arabic."
    )
}

# Select which prompt to use here:
SELECTED_PROMPT = PROMPT_TEMPLATES["tech_translation"]
# Change to PROMPT_TEMPLATES["tech_summary"] if you want a summary instead.

# --------------------------------------------------------

def split_text_smart(text, max_length):
    """Splits text without breaking sentences."""
    chunks = []
    while len(text) > max_length:
        # Try splitting at paragraph end
        split_index = text.rfind('\n', 0, max_length)
        # If no paragraph, try sentence end
        if split_index == -1:
            split_index = text.rfind('.', 0, max_length)
        # If no sentence, try space
        if split_index == -1:
            split_index = text.rfind(' ', 0, max_length)
        # Last resort: hard cut
        if split_index == -1:
            split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def process_segment(text_chunk, retries=3):
    """Sends the chunk to Ollama with the selected engineering prompt."""

    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SELECTED_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.1, # Low temp = High precision (Technical Writer style)
                    'top_p': 0.9,
                }
            )
            return response['message']['content']
        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Error: {e}")
            time.sleep(2)

    return "[Error: Segment failed to process]"

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found.")
        return

    print("--- Starting Process with 'Expert Technical Writer' Persona ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    # Clear output file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    # Process chunks
    for chunk in tqdm(chunks, desc="Processing"):
        result = process_segment(chunk)

        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(result + "\n\n")

    print(f"\n[Success] Task complete! Saved to: {OUTPUT_FILE}")

    # Preview
    print("-" * 30)
    print("Output Preview:")
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()

"""--- Starting Process with 'Expert Technical Writer' Persona ---
Document split into 1 parts.

Processing: 100%
 1/1 [05:35<00:00, 335.66s/it]


[Success] Task complete! Saved to: output_arabic.txt
------------------------------
Output Preview:
يُعرَف الذكاء الاصطناعي (AI) بأنه الحكمة التي تظهرها الآلات، على عكس الحكمة الطبيعية التي تتميز بها الحيوانات بما في ذلك البشر.

وقد تم تعريف البحث عن الذكاء الاصطناعي بأنها مجال دراسة एजنسيات ذكية، والتي تشير إلى أي نظام يدرك بيئته ويتخذ إجراءات تزيد من فرص تحقيق أهدافه.

ومع ذلك، استُخدم المصطلح "ذكاء اصطناعي" سابقًا لوصف الآلات التي تقلد وتظهر مهارات认مية بشرية مرتبطة بالدماغ البشري، مثل "التعلم" و " حل المشكلات".

وقد تم رفض هذا التعريف منذ ذلك الحين من قبل باحثي الذكاء الاصطناعي البارزين الذ...
------------------------------
### New Section

https://github.com/mrseanryan/gpt-summarizer/blob/9dd9ae6bf70de990294a14d28d027821e5e530f1/gpt_summarizer/prompts.py#L5
"""

import ollama
import os
import time
from tqdm.notebook import tqdm

# ------------------- Configuration -------------------
INPUT_FILE = "text.txt"
OUTPUT_FILE = "output_arabic_v2.txt"
MODEL_NAME = "llama3.1:8b"
CHUNK_SIZE = 1000  # Smaller chunks reduce hallucination risks

# ------------------- ENGINEERED PROMPT (Anti-Glitch) -------------------
# Updated based on your request + constraints to fix Hindi/Chinese glitches

PROMPT_TEMPLATES = {
    "strict_tech_translation": (
        "ROLE: You are an expert Computer Science Translator specialized in AI.\n"
        "TASK: Translate the text to Modern Standard Arabic (Fusha).\n\n"
        "CRITICAL RULES (MUST FOLLOW):\n"
        "1. NO GLITCHES: Do NOT use Hindi characters (e.g., 'ए'), Chinese (e.g., '认'), or mixed scripts. Use ONLY Arabic letters.\n"
        "2. TERMINOLOGY MAPPING:\n"
        "   - 'Artificial Intelligence' -> 'الذكاء الاصطناعي' (NOT 'حكمة' or 'تعلم إلكتروني').\n"
        "   - 'Intelligence' -> 'ذكاء'.\n"
        "   - 'Agents' -> 'وكلاء' or 'كيانات' (NOT 'एजنسيات').\n"
        "   - 'Cognitive' -> 'إدراكية' or 'معرفية'.\n"
        "3. STYLE: Academic, concise, and professional.\n"
        "4. OUTPUT: Provide the Arabic translation ONLY. No intro, no notes."
    )
}

SELECTED_PROMPT = PROMPT_TEMPLATES["strict_tech_translation"]

# --------------------------------------------------------

def split_text_smart(text, max_length):
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind('\n', 0, max_length)
        if split_index == -1: split_index = text.rfind('.', 0, max_length)
        if split_index == -1: split_index = text.rfind(' ', 0, max_length)
        if split_index == -1: split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def process_segment(text_chunk, retries=3):
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SELECTED_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.3,  # Increased slightly to avoid "Hindi token trap"
                    'top_p': 0.9,
                    'repeat_penalty': 1.1, # Penalize repetition/glitches
                    'num_predict': 2048,   # Allow enough space for output
                }
            )

            content = response['message']['content']

            # Simple check: If output contains Hindi/Chinese chars, retry
            # (Very basic filter logic)
            if any("\u0900" <= c <= "\u097F" for c in content): # Hindi block
                raise ValueError("Detected Hindi characters in output!")

            return content

        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed/rejected. Reason: {e}")
            time.sleep(1)

    return "[Error: Translation Failed]"

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found.")
        return

    print("--- Starting Process (Strict Anti-Glitch Mode) ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        result = process_segment(chunk)
        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(result + "\n\n")

    print(f"\n[Success] Task complete! Saved to: {OUTPUT_FILE}")

    print("-" * 30)
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:600] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()

!pip install pdfplumber

import pdfplumber

def extract_text_from_pdf(pdf_path, output_txt_path):
    """
    تستخرج النص من ملف PDF وتحفظه في ملف نصي بنفس التنسيق التقريبي (فقرات وسطور).

    :param pdf_path: مسار ملف PDF الأصلي
    :param output_txt_path: مسار الملف النصي المطلوب حفظه
    """
    extracted_text = []

    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page_num, page in enumerate(pdf.pages, start=1):
                # استخراج النص مع الحفاظ على السطور
                text = page.extract_text()
                if text:
                    extracted_text.append(text)
                    # إضافة فاصل بين الصفحات (اختياري)
                    extracted_text.append("\n" + "="*50 + f" صفحة {page_num} " + "="*50 + "\n")
                else:
                    print(f"لم يتم العثور على نص في الصفحة {page_num}")

        # كتابة النص المستخرج في ملف نصي
        with open(output_txt_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(extracted_text))

        print(f"✅ تم حفظ النص المستخرج في: {output_txt_path}")

    except Exception as e:
        print(f"❌ حدث خطأ أثناء معالجة الملف: {e}")

# === الاستخدام ===
if __name__ == "__main__":
    # غيّر هذه المسارات حسب ملفك
    pdf_file = "/content/Dracula (Novel)_1-5.pdf"          # اسم ملف PDF (يجب أن يكون في نفس المجلد أو أعط مسارًا كاملاً)
    output_file = "النص_المستخرج.txt"  # اسم الملف النصي الناتج

    extract_text_from_pdf(pdf_file, output_file)

import ollama
import os
import time
from tqdm.notebook import tqdm

# ------------------- Configuration -------------------
INPUT_FILE = "/content/1.txt"
OUTPUT_FILE = "translated_general.txt"
MODEL_NAME = "llama3.1:8b"
# Chunk size: 1000-1200 is safe for maintaining context without memory issues
CHUNK_SIZE = 1200

# ------------------- GENERAL SYSTEM PROMPT -------------------
# This prompt is designed to work with ANY text type (technical, story, news, etc.)
# It focuses on language purity and style, not specific words.

SYSTEM_PROMPT = (
    "ROLE: You are an expert linguist and professional translator.\n"
    "TASK: Translate the provided text into fluent, high-quality Modern Standard Arabic (Fusha).\n"
    "GUIDELINES:\n"
    "1. Context Awareness: Analyze the text to understand the context. If it is technical, use technical Arabic terms. If it is narrative, use descriptive Arabic.\n"
    "2. Language Purity: The output must be strictly in Arabic script. Do NOT use Hindi, Urdu, or Chinese characters under any circumstances.\n"
    "3. Grammar: Ensure correct grammar and sentence structure.\n"
    "4. formatting: Maintain the original paragraph structure.\n"
    "5. OUTPUT: Provide ONLY the Arabic translation. Do not add notes like 'Here is the translation'."
)

# -------------------------------------------------------------

def split_text_smart(text, max_length):
    """
    Splits text efficiently without breaking sentences.
    """
    chunks = []
    while len(text) > max_length:
        # Priority 1: Split at a newline (paragraph end)
        split_index = text.rfind('\n', 0, max_length)

        # Priority 2: Split at a period (sentence end)
        if split_index == -1:
            split_index = text.rfind('.', 0, max_length)

        # Priority 3: Split at a space (word end)
        if split_index == -1:
            split_index = text.rfind(' ', 0, max_length)

        # Fallback: Hard split if no separators found
        if split_index == -1:
            split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    """
    Translates a chunk with retry logic to handle potential model hiccups.
    """
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SYSTEM_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    # Temperature 0.3 allows the model enough flexibility to pick
                    # the right Arabic words without getting stuck in a loop (which causes glitches).
                    'temperature': 0.3,
                    'top_p': 0.9,
                    'num_predict': 2048,
                }
            )

            content = response['message']['content']
            return content

        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Error: {e}")
            time.sleep(1)

    return "[Error: Segment translation failed]"

def main():
    # 1. Validation
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found. Please upload it.")
        return

    print("--- Starting General Translation ---")

    # 2. Read File
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    # 3. Split
    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    # 4. Prepare Output File
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    # 5. Process
    for chunk in tqdm(chunks, desc="Translating"):
        result = translate_segment(chunk)

        # Append immediately to file
        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(result + "\n\n")

    print(f"\n[Success] Process complete! File saved as: {OUTPUT_FILE}")

    # 6. Preview
    print("-" * 30)
    print("Preview of the result:")
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:600] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()



"""https://huggingface.co/CohereLabs/aya-expanse-8b

https://huggingface.co/CohereLabs/c4ai-command-r7b-arabic-02-2025

https://huggingface.co/bartowski/aya-expanse-32b-GGUF/tree/main

https://huggingface.co/bartowski/aya-expanse-8b-GGUF/tree/main

https://huggingface.co/spaces/CohereLabs/command-a-translate

https://huggingface.co/bartowski/CohereLabs_command-a-reasoning-08-2025-GGUF/tree/main/CohereLabs_command-a-reasoning-08-2025-Q3_K_M

https://huggingface.co/bartowski/c4ai-command-r7b-12-2024-GGUF/tree/main
"""

https://huggingface.co/CohereLabs/c4ai-command-r7b-12-2024


Languages covered: The model has been trained on 23 languages: English, French, Spanish, Italian, German, Portuguese, Japanese, Korean, Arabic, Chinese, Russian, Polish, Turkish, Vietnamese, Dutch, Czech, Indonesian, Ukrainian, Romanian, Greek, Hindi, Hebrew, and Persian.

Context length: Command R7B supports a context length of 128K.



/content/translated_general.txt
دراكولا
من تأليف برام ستوكر
المطبوعة عام 1897
الفصل الأول
سجل جوناثان هاركر
3 مايو. بستريتسيز. - غادرنا ميونخ في الساعة الثامنة والثلاثين مساءً في اليوم الأول من مايو، ووصلنا إلى فيينا في الصباح الباكر التالي، كان يجب أن نصل في الساعة السادسة وأربعين دقيقة، لكن القطار تأخر ساعة واحدة.
يبدو أن بودابست مكان رائع، من نظرة ما استطعتها من خلال القطار وبالقرب الذي استطعت المشي فيه من الشوارع. خفت أن آتي بعيدًا عن المحطة، لأننا وصلنا متأخرون وسوف نغادر في الوقت الصحيح قدر الإمكان.
ال impression التي حصلت عليها هي أننا نترك الغرب وندخل الشرق؛ أكثر الجسور المذهلة في العالم يربط بين الغرب والشرق، وهي جسر على النهر الدانوب الذي هنا من العرض الكبير والمعمولة العميقة، ووضعنا بين التقاليد الحاكمة للعثمانيين.

================================================== صفحة 1 ==================================================

غادرنا في وقت جيد نسبيًا، ووصلنا بعد غروب الشمس إلى كلوسنبرج. توقفت هنا ليلتني في فندق رويال. أكلت في الغداء أو بالأحرى العشاء، دجاجة مطهورة بطريقة معينة باستخدام الفلفل الأحمر، كانت طعمة جيدة ولكن جفيفة. (ملاحظة: احصل على وصفة لها ل مينا). سألت الخادم، وقال لي إنها تسمى "باپريكا هينديل"، وأنها طعام وطني، nên يجب أن أستطيع الحصول عليها في أي مكان.

في أي مكان على جبال الكاربات.
وجدت أن معرفتي القليله باللغة الألمانية كانت مفيدة هنا، و لا أعرف كيف سأستطيع العيش بدونها.
بعدما استفدت من بعض الوقت الذي كان متوفرا لي في لندن، زرت المتحف البريطاني وقمت ببحث بين الكتب والخرائط في المكتبة حول تراسيا، و أدركت أن المعرفة القليله بالبلاد سوف تكون مهمة في التعامل مع نبيل من تلك البلاد.
أنا وجدت أن المنطقة التي ذكرها هو في أقصى شرق البلاد، على حدود ثلاث دول: تراسيا ومولدافيا وبوكوفينا، وسط جبال الكاربات؛ واحدة من أجزاء أوروبا الأشد غموضاً وعدم المعرفة.
لم استطع العثور على أي خريطة أو عمل يبين موقع قصر دراكولا بدقة، لأن لا توجد خرائط لهذه البلاد حتى الآن مثل خرائط المسح الجغرافي البريطاني التي نستخدمها؛ لكنني وجدت أن بستريتز، المدينة المحلية المذكورة من قبل كونت دراكولا، هي بلدة معروفة.
سأضيف هنا بعض ملاحظاتي، حيث قد تساعدني في استعادة الذاكرة عندما أتحدث مع مينا عن رحلاتي.
في سكان تراسيا هناك أربع طوائف مختلفة:
(Translation continues...)

في الجنوب Saxons، وهم مخلوطون بWallachs، الذين هم أحفاد Dacians؛ في الغرب Magyars، وفي الشرق والشمال Szekelys. أنا أذهب إلى الأخير، الذين يزعمون أنهم من ذريّة Attila وحمّال الهواء. قد يكون هذا صحيحًا، فإذا كان Magyars قد غزوا البلاد في القرن الحادي عشر، وجدوا حمّال الهواء مقيمين فيها.

قرأت أن كل ما يعرف من خرافات العالم جمع في حلق Carpathians، كأنها مركز لبعض نوع من الدوران الخيالي؛ فربما تكون إقامتاي مثيرة. (ملاحظة، يجب أن أسأل الكونت عنهم.)

لم أستريح جيدًا، رغم أن سريري كان مريحًا، لأنني كنت أفكر في كل sorts of أحلام غريبة. كانت هناك كلبة تصرخ طوال الليل تحت نافذتي، وقد يكون لها علاقة بهذا؛ أو قد يكون من paprika، لأنني يجب أن أسقي كأس الماء في كاريفي، وازدادت جفافي. نحو الفجر استيقظت وأصبحت مستيقظًا بسبب الضرب المستمر على بابي، فبدو لي أنه كنت أستريح جيدًا آنذاك.

كنت قد أكلت في الصباح أكثر من البابريكا، و نوعًا من الحساء من دقيق الذرة الذي قالوا إنه "ماماليكا"، و خضروة فلفل ممتلئة بالدجاج المقطّع، وجدت هذه الأكل جيدًا جدًا، ويسمونها "إمبلاتا". (مذكورة: حصل على الوصفة لهذا الأكل أيضًا.)

كان علي أن أسرع في الأكل لأن القطار بدأ قبل الساعة الثامنة قليلًا، أو ربما كان يجب أن يبدأ بذلك، لأنه بعد سير إلى المحطة في الساعة 7:30 كان علي أن أجلس في القطار لمدة أكثر من ساعة قبل أن نبدء الحركة.

يبدو لي أن كلما اتجهنا شرقًا زادت عدم دقتهم. ماذا يجب أن يكونوا في الصين؟

كانت اليوم تبدو وكأننا نستغرق في بلاد مليئة بالجمال من كل نوع. أحيانًا رأينا مدن صغيرة أو قصور على قمم جبال مرتفعة مثل تلك التي نراها في القصص المقدسة; وأحيانًا سرعنا بسهولة عبر أنهار وآبار يبدو من الحافة الحجريّة الواسعة من كل جانب منها أنها عرضة للفيضانات الكبيرة. تحتاج كمية كبيرة من الماء، وسرعة قوية، لتنظيف حافة خارجيّة لنهر.

في كل محطة كان هناك مجموعات من الناس، أحيانًا تجمعات، وجميعهم يرتدون ملابس مختلفة. بعضهم كانوا مثل الفلاحين في الوطن أو الذين رأيت في...

كانوا يأتون من فرنسا وألمانيا، يرتدون قميص قصير وطربوش مستدير وقمصان أصلية، ولكن كان بعضهم يبدو متميزاً.

نظروا إلى النساء جميلات في البداية، لكن عندما اقتربنا منهن، اكتشفنا أنهن يبدون غير متكاملات في الخصر. كانت جميعهن تلبسن كُمّين بيض آملين من نوع ما، وبالإضافة إلى ذلك، كان معظمهن يرتدين حزاماً كبيراً مزخرفاً بالعديد من الأشرطة التي تتمايل مثل القصبات في الباليه، ولكن طبعاً، كانت هناك قميصات تحتها.

أكبر ما شاهدناه من حيث الظرافة كان السلوڤاكيون، الذين كانوا أكثر بربرية من باقي الناس، مع أطواد رفيعة كبيرة وقمصان بيضاء متسخة كبيرة وقمصان من القطن البيض الأبيض، وحزامين كبيرين من الجلد الثقيل، يبلغ عرضهم تقريباً قدمًا واحدًا، مزخرفين بالعديد من النجوم البرونزية. كانوا يرتدون حذاء عالي، مع تثبيت قميصهم في داخله، وكان لديهم شعر أسود طويل ومستأصلة أسود ثقيلة. هم أصحاب مظهر جميل، لكن لا يبدو أنهن يمتلكن المظهر الجذب. لو كانوا على المسرح، لكانوا تمثيلًا قديمًا من فرقة عرائس بربرية شرقية. ومع ذلك، وفقاً للمعلومات التي تلقيتها، هم أفراد هينون ومتخاذلون في التعبير عن احتياجاتهم الطبيعية.

كانت الساعة متأخرة من الليل عندما وصلنا إلى بستريتز، وهي مدينة قديمة ومثيرة. يقع على حافة البلاد -فإن ممر بورغو يؤدي منها إلى بوكوفينا- ولذلك فقد عانى من وجودها حياة مضطربة ويتضح ذلك في كل مكان. قبل خمسين عاماً حدثت سلسلة من الحوادث الكبرى، مما أسفر عن دمار كبير على خمس مناسبات مختلفة. وفي بداية القرن السابع عشر تعرضت للاستيلاء على مدة ثلاثة أسابيع ووقعت 13 ألف قتيل، وكانت الخسائر في الحرب تزداد سوءاً بسبب الجوع والمرض.

أمرني كونت دراكولا بالذهاب إلى فندق الكرون الذهبي، الذي وجدته بمظهر قديم جداً، لأنني كنت أريد أن أرى كل ما يمكنني من شئون البلد.

كانت هناك توقعات بأنني سأكون هناك، فعندما اقتربت من الباب واجهت امرأة مسنة طيبة المظهر ترتدي ملابس الفلاحين العادية -لباس أسفل أبيض مع فستان ضخم ملون يصل إلى الكتف- عندما اقتربت منها قالت: "هو السيد الإنجليزي؟" قلت لها: "نعم، جوناثان هاركر." ابتسمت وارسلت رسالة إلى رجل مسن يرتدي قميصاً أبيضاً، كان قد اتبعها إلى الباب.

ذهب، لكنه عاد فورًا مع بريد:
"أحِبُّكَ.--أُرحَبُ لكَ بالكاربات. أَنظُرُ إلى وصولكِ بِالحرص. استَرقِ اللَيْلَ جيدًا. في الثَلاثِة غدًا سيبدأ السَفَرُ لِبُكوڤينا، ويُحتفظُ بمكانٍ لكَ فيهِ. في مضيق البورغو سوف ينتظركِ عربتي وسيأخذكِ إلَيَّ. أَتمنى أن يكونَ سفرك من لندن سعيدًا، وأن تُسَرَّعَ في إقامتك في أرضي الجميلة.--أَحِبُّكَ,
دروكولا."
4 مايو- وجدتُ أنّ أهلي قد حصلوا على بريدٍ من القسيس، يَدِرُهُم بِحجز أفضل مكانٍ في السَفَرِ لي؛ لكن عند سؤالهم عن تفاصيلِهِ بدوا مترددين، واعترفوا بأَنَّهم لا يستطيعون فهمي الألمانية.

================================================== صفحة 4 ==================================================

لا يمكن أن يكونَ هذا الصادقًا، لأنّهم كانوا يفهمونها جيدًا حتى ذلك الحين؛ على الأقل، كانت الإجاباتُ لأسئلتي دقيقةً كأَنَّهم يستطيعون فهمها. وقف الزعيم وزوجته، السيدة المسنة التي استقبلتني، ينظران بعضهما البعض بِنظرة خوفية نوعًا ما. بدا أنّ المال قد أُرسِلَ في بريدٍ، وأَنَّ ذلك كل ما يعرفونه. عندما سألتهُم إن كانوا يعرفون القسيس دروكولا،

وكانا يصليان الصلاة، ويتقادمان، وقالوا إنهما لا يعرفان شيئًا من ذلك، فلم يتحدثا أيًا. كان الوقت قريبًا من انطلاق السفر، ولم أكن لدي وقت لأسألใครًا آخر، لأن كل شيء كان غامضًا ومثيرًا للخوف.

وكانت السيدة العجوز تحضر إلى غرفتي قبل أن أخرج، وقالت بحركة هستيرية: "لا يجب أن تذهب؟ يا شاب الهير! لا يجب أن تذهب؟" كانت في حالة من التهيج الشديد حتى فقدت سيطرتها على اللغة الألمانية التي تعلمتها، وخلطت بينها وبين لغة أخرى لا أعرفها.

كنت أستطيع اتباع كلامها عن طريق أسئلة متكررة. عندما قلت لها إنني يجب أن أذهب الآن، وأنني مشغول في شؤون مهمة، سألت مرة أخرى: "هل تعرف ما اليوم؟" أجبتها أن اليوم الرابع من مايو.

وقفت رأسها وهي تقول مرة أخرى: "نعم! أعرف ذلك! أعرف ذلك، ولكن هل تعرف ما اليوم؟" عندما قلت لها إنني لا أفهم،続ت على قائلي:

"هو اليوم قبل عيد القديس جورج. هل لا تعرف أن هذا الليل، عند صوت الساعة في منتصف الليل، سيتمتع كل الشرور في العالم بالسيطرة؟ هل لا تعرف ذلك؟

عرفت مكانك و ما ستذهب إليه؟ كانت في حالة من القلق البليغ، فحاولت أن أطمئنها دون جدوى. ثم انهضت على ركبتي وتوسلت إليّ أن لا أغادرها؛ على الأقل أن آخُذ يومًا أو اثنين قبل الخروج.

كان كل ذلك أمرًا سخيفًا، لكنني لم أشعر بالراحة. ومع ذلك، كان هناك أعمال يجب إنجازها، ولا يمكن لي أن ألوي أي شيء من أجلها.

حاولت أن أعيدها على قوتها وقولت لها بجدية ما شكرتها، لكن واجبي كان أمرًا لازمًا، وبالتالي يجب عليّ الخروج.

ثم站ت وأسقمت عينيها، ثم أخذت صليبًا من حول عنقها وقدمته لي.

"""رأيي بصراحة: الترجمة جيدة كبداية لفهم المعنى العام، ولكنها "غير صالحة للنشر" أو القراءة الممتعة بوضعها الحالي.

إليك تحليلي التفصيلي للمشاكل الموجودة في النص (ولماذا حدثت)، وكيفية إصلاحها برمجياً:
1. المشاكل الكبرى في النص (The Issues):

    بقايا الإنجليزية (Code Switching):
    النموذج "تكسال" عن ترجمة بعض الكلمات وتركها كما هي:

        أمثلة: impression، Saxons، Wallachs، Magyars، paprika، sorts of.

        السبب: النموذج اعتبر هذه الكلمات مصطلحات علمية أو أسماء لا تترجم، أو أن "الموجه" لم يكن صارماً بما يكفي لتعريب الأسماء.

    "خلل" الحروف الصينية (Glitches):
    ظهرت حروف صينية وسط الكلمات العربية!

        أمثلة: 续ت (بدلاً من "استمرت")، 站ت (بدلاً من "وقفت").

        السبب: هذا يحدث غالباً عندما تكون الـ Temperature منخفضة جداً (0.1)، مما يجعل النموذج يعلق في "توكن" خاطئ ولا يستطيع الخروج منه.

    أخطاء في المعنى (كارثية ومضحكة):

        "أحبك... دراكولا": ختم الرسالة بكلمة "أحبك"! (في النص الأصلي "Your friend" أو "Yours"). دراكولا وحش مرعب وليس محباً ولهاناً! 😂

        "القسيس": يبدو أنه ترجم كلمة ما خطأً، فدراكولا هو "كونت" (Count) وليس قسيساً.

    الركاكة اللغوية:

        جمل مثل "ال impression التي حصلت عليها" ضعيفة جداً.
"""







import ollama
import os
import time
import re
from tqdm.notebook import tqdm

# ------------------- Configuration -------------------
INPUT_FILE = "text.txt"
OUTPUT_FILE = "dracula_arabic.txt"
MODEL_NAME = "llama3.1:8b"
CHUNK_SIZE = 1200

# ------------------- LITERARY SYSTEM PROMPT -------------------
# هذا الموجه مخصص للأدب والروايات
# يطلب من النموذج تعريب الأسماء (Transliteration) بدلاً من تركها بالإنجليزية
SYSTEM_PROMPT = (
    "ROLE: You are a professional literary translator aimed at Arab readers.\n"
    "TASK: Translate the novel text into fluent, captivating Modern Standard Arabic.\n"
    "CRITICAL RULES:\n"
    "1. NO ENGLISH LEFT: You must transliterate proper names (e.g., 'Saxons' -> 'السكسونيون', 'Bistritz' -> 'بيستريتز'). Do not leave ANY Latin characters.\n"
    "2. NO GLITCHES: Do NOT use Chinese characters (like 站, 续) or Hindi characters. Use ONLY Arabic script.\n"
    "3. TONE: Maintain the atmospheric, gothic, and antique tone of the novel (19th century style).\n"
    "4. ACCURACY: Translate 'Count' as 'الكونت' (not priest). Translate endings like 'Yours' as 'المخلص لك' (not I love you).\n"
    "5. OUTPUT: Provide ONLY the Arabic text."
)

def remove_foreign_chars(text):
    """
    دالة تنظيف إضافية لإزالة أي حروف صينية أو إنجليزية قد تتسرب
    """
    # السماح فقط بالعربية، الأرقام، وعلامات الترقيم الأساسية
    # هذا التعبير النمطي (Regex) يحذف الحروف اللاتينية والصينية والهندية
    clean_text = re.sub(r'[a-zA-Z]', '', text) # حذف الإنجليزية
    # (يمكن إضافة المزيد من الفلاتر هنا إذا لزم الأمر)
    return clean_text

def split_text_smart(text, max_length):
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind('\n', 0, max_length)
        if split_index == -1: split_index = text.rfind('.', 0, max_length)
        if split_index == -1: split_index = text.rfind(' ', 0, max_length)
        if split_index == -1: split_index = max_length
        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()
    if text: chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SYSTEM_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.4, # رفعنا الحرارة قليلاً للسرد القصصي
                    'top_p': 0.9,
                    'num_predict': 2048,
                }
            )

            content = response['message']['content']

            # التحقق من وجود حروف صينية شائعة في الأخطاء
            if any(char in content for char in ['站', '续', '是', '的']):
                 raise ValueError("Detected Chinese glitch characters!")

            return content

        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Reason: {e}")
            time.sleep(1)

    return "[Translation Failed for this part]"

def main():
    if not os.path.exists(INPUT_FILE):
        print("File not found.")
        return

    print("--- Starting Literary Translation (Dracula Mode) ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Split into {len(chunks)} parts.")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        result = translate_segment(chunk)

        # تنظيف إضافي (اختياري)
        # result = remove_foreign_chars(result)

        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(result + "\n\n")

    print(f"\n[Done] Check {OUTPUT_FILE}")

    # عرض عينة
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")

if __name__ == "__main__":
    main()







import ollama
import os
import time
import re
from tqdm.notebook import tqdm

# ------------------- Settings -------------------
INPUT_FILE = "/content/1.txt"           # The file you want to translate
OUTPUT_FILE = "translated_general.txt"
MODEL_NAME = "llama3.1:8b"
CHUNK_SIZE = 1000                 # Safe size to keep context

# ------------------- UNIVERSAL SYSTEM PROMPT -------------------
# This prompt guides the AI to behave like a human translator
# regardless of the text type (Fiction, Non-fiction, etc.)

SYSTEM_PROMPT = (
    "ROLE: You are an expert professional translator proficient in English and Modern Standard Arabic (Fusha).\n"
    "TASK: Translate the provided text into natural, fluent Arabic.\n"
    "GUIDELINES:\n"
    "1. TRANSFORMATION: Do not translate word-for-word. Translate the *meaning* and *context*.\n"
    "2. PROPER NOUNS: Transliterate names and places into Arabic phonetically (e.g., 'London' -> 'لندن', 'Harker' -> 'هاركر'). Do NOT leave them in English.\n"
    "3. IDIOMS: Adapt idioms and letter closings to their Arabic equivalents (e.g., 'Yours' at end of letter -> 'المخلص لك').\n"
    "4. SCRIPT: The output must be 100% Arabic script. Do not use Hindi/Chinese characters.\n"
    "5. PUNCTUATION: Adjust punctuation to suit Arabic writing standards."
)

# ---------------------------------------------------------------

def split_text_smart(text, max_length):
    """
    Splits text attempting to keep paragraphs and sentences intact.
    """
    chunks = []
    while len(text) > max_length:
        # Priority 1: Newline (Paragraph)
        split_index = text.rfind('\n', 0, max_length)

        # Priority 2: Period (Sentence)
        if split_index == -1:
            split_index = text.rfind('.', 0, max_length)

        # Priority 3: Space (Word)
        if split_index == -1:
            split_index = text.rfind(' ', 0, max_length)

        # Fallback
        if split_index == -1:
            split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    """
    Translates a chunk with retry logic to handle model instability.
    """
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SYSTEM_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    # Temperature 0.35 is balanced:
                    # High enough to be creative with literary text.
                    # Low enough to avoid hallucinations/glitches.
                    'temperature': 0.35,
                    'top_p': 0.9,
                    'num_predict': 2048,
                }
            )

            content = response['message']['content']

            # Basic sanity check: If output is empty, retry
            if not content.strip():
                raise ValueError("Empty response received")

            return content

        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Reason: {e}")
            time.sleep(1)

    return "[Error: Could not translate this segment]"

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found.")
        return

    print("--- Starting General Translation ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    # Clear output file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    # Process
    for chunk in tqdm(chunks, desc="Translating"):
        result = translate_segment(chunk)

        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(result + "\n\n")

    print(f"\n[Success] Translation saved to: {OUTPUT_FILE}")

    # Preview
    print("-" * 30)
    print("Preview:")
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:600] + "...")
    print("-" * 30)

if __name__ == "__main__":
    main()

""":
1. التحسن الملحوظ (الجيد):

    اختفاء الأحرف الصينية والهندية: لم تعد تظهر رموز غريبة مثل 续 أو एज، وهذا إنجاز كبير بفضل الفلاتر وضبط الحرارة.

    القضاء على الإنجليزية: معظم الكلمات تُرجمت أو عُرّبت (مثل "بستريتز"، "ببريكا هانديل").

    السرد مفهوم: يمكنك قراءة النص وفهم القصة وتتابع الأحداث.

2. المشاكل المستمرة (التي تحتاج لحل):

    بطء شديد: ذكرت أن الترجمة "استمرت وقت كبير". هذا متوقع لأن النموذج Llama 3.1 8B ثقيل نسبياً على المعالج (CPU).

    بقايا تعليمات (Leaking): النموذج ما زال يطبع ملاحظات بالإنجليزية وسط النص العربي!

        مثال: Note: I followed the guidelines...

        مثال: Note: Transliteration of "St. George's Day"...

        مثال: appearanceاً (كلمة إنجليزية مدمجة بتنوين عربي! هذا "Glitch" جديد ومضحك).

    أخطاء ترجمة السياق:

        "أحبك... دراكولا": ما زالت موجودة! لم يفهم أن Yours تعني "المخلص لك".

        "أجنبي إنجليزي؟": (The English Herr?) ترجمها "الأجنبي" بدلاً من "السيد".

        "الدوقة دراكولا": حول الكونت إلى أنثى (دوقة)!

الحل لمشكلة البطء + الجودة (The Final Optimization)

لحل مشكلة البطء، سنقوم بخطوتين:

    تفعيل تسريع GPU (إجباري): ذكرت في البداية أنك تستخدم Colab. يجب التأكد من أنك تستخدم T4 GPU وليس المعالج فقط.

    استخدام نموذج أصغر (Phi-3 Mini): إذا كنت مصراً على السرعة الفائقة، فنموذج Phi-3 من مايكروسوفت (3.8 مليار بارامتر) أسرع بـ 3 أضعاف من Llama 3 (8 مليار)، وجيد جداً في الترجمة.

إليك الكود المحدث بالكامل الذي:

    يستخدم نموذج Phi-3 (الأسرع والأخف).

    يحتوي على فلتر صارم (Strict Cleaner) يحذف أي ملاحظات إنجليزية (Note: ...) من الناتج النهائي قبل حفظه.


"""

import ollama
import os
import re
import time
from tqdm.notebook import tqdm

# ------------------- Settings -------------------
INPUT_FILE = "text.txt"
OUTPUT_FILE = "translated_generic.txt"
MODEL_NAME = "llama3.1:8b"  # Best balance for quality
CHUNK_SIZE = 1000           # Optimal size for context

# ------------------- GENERIC SYSTEM PROMPT -------------------
# No hardcoded dictionaries. Relies on the model's intelligence.
SYSTEM_PROMPT = (
    "ROLE: You are a professional translator proficient in English and Modern Standard Arabic.\n"
    "TASK: Translate the provided text into fluent, natural Arabic based on the context.\n"
    "RULES:\n"
    "1. CONTEXT: Analyze the text style (narrative, technical, or formal) and translate accordingly.\n"
    "2. NO NOTES: Do NOT provide explanations, headers, or notes like 'Here is the translation'. Output ONLY the Arabic text.\n"
    "3. SCRIPT: Use only Arabic script. Transliterate proper names if necessary.\n"
    "4. PUNCTUATION: Adjust punctuation to match Arabic standards."
)

def remove_english_artifacts(text):
    """
    Filters out lines that contain mostly English characters.
    This solves the issue of 'Note: I followed the guidelines...' appearing in the output.
    """
    lines = text.split('\n')
    cleaned_lines = []

    for line in lines:
        # Check if the line has English letters
        if re.search(r'[a-zA-Z]', line):
            # Count English vs Arabic chars
            english_char_count = len(re.findall(r'[a-zA-Z]', line))
            total_len = len(line.strip())

            # If a line is more than 30% English, discard it (it's likely a note)
            if total_len > 0 and (english_char_count / total_len) > 0.3:
                continue

        cleaned_lines.append(line)

    return '\n'.join(cleaned_lines).strip()

def split_text_smart(text, max_length):
    chunks = []
    while len(text) > max_length:
        # Split by paragraph first
        split_index = text.rfind('\n', 0, max_length)
        if split_index == -1: split_index = text.rfind('.', 0, max_length)
        if split_index == -1: split_index = text.rfind(' ', 0, max_length)
        if split_index == -1: split_index = max_length

        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()

    if text:
        chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SYSTEM_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.3, # Balanced for general use
                    'num_predict': 2048,
                }
            )

            content = response['message']['content']

            # Apply the filter to remove English notes immediately
            cleaned_content = remove_english_artifacts(content)

            return cleaned_content

        except Exception as e:
            print(f"\n[Warning] Attempt {attempt+1} failed. Error: {e}")
            time.sleep(1)

    return "" # Return empty string on failure rather than error message

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[Error] File '{INPUT_FILE}' not found.")
        return

    print("--- Starting General Translation ---")

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"Document split into {len(chunks)} parts.")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        result = translate_segment(chunk)

        if result:
            with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
                f.write(result + "\n\n")

    print(f"\n[Success] Done! Saved to: {OUTPUT_FILE}")

    # Preview
    if os.path.exists(OUTPUT_FILE):
        print("-" * 30)
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
        print("-" * 30)

if __name__ == "__main__":
    main()

"""

للحصول على سرعة عالية جداً ومساحة صغيرة (أقل من 2 جيجا) مع دعم جيد للعربية، أنصحك باستخدام موديل Gemma 2 (نسخة 2B) من جوجل، أو Qwen 2.5 (نسخة 1.5B).

إليك الخيارات الأخف على الإطلاق:

    gemma2:2b (الحجم: 1.6 جيجا فقط) -> ممتاز وسريع جداً.

    qwen2.5:1.5b (الحجم: 1.1 جيجا فقط) -> طيارة (أسرع شيء ممكن).

    phi3:mini (الحجم: 2.3 جيجا) -> النسخة الصغيرة من Phi3 (أخف بكثير من Medium)."""

!ollama pull gemma2:2b

!ollama list

import ollama
import os
import re
import time
from tqdm.notebook import tqdm

# ------------------- Settings -------------------
INPUT_FILE = "/content/1.txt"
OUTPUT_FILE = "translated_fast.txt"

# اخترنا هذا الموديل لأنه خفيف جداً (1.6 GB) ويدعم العربية
MODEL_NAME = "gemma2:2b"
# بديل آخر سريع جداً: "qwen2.5:1.5b"

CHUNK_SIZE = 800  # حجم أصغر لسرعة أكبر

# ------------------- SYSTEM PROMPT -------------------
SYSTEM_PROMPT = (
    "ROLE: Professional Translator.\n"
    "TASK: Translate text to Arabic.\n"
    "RULES:\n"
    "1. OUTPUT: Arabic only. No English characters. No Notes.\n"
    "2. NAMES: Transliterate names (e.g., Jonathan -> جوناثان).\n"
    "3. MEANING: Translate context, not word-for-word."
)

def remove_english_artifacts(text):
    """Filter out English noise"""
    lines = text.split('\n')
    cleaned_lines = []
    for line in lines:
        if re.search(r'[a-zA-Z]', line):
            english_char_count = len(re.findall(r'[a-zA-Z]', line))
            if len(line) > 0 and (english_char_count / len(line)) > 0.4:
                continue
        cleaned_lines.append(line)
    return '\n'.join(cleaned_lines).strip()

def split_text_smart(text, max_length):
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind('\n', 0, max_length)
        if split_index == -1: split_index = text.rfind('.', 0, max_length)
        if split_index == -1: split_index = max_length
        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()
    if text: chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SYSTEM_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.2, # حرارة منخفضة للسرعة والدقة
                    'num_predict': 1024,
                }
            )
            content = response['message']['content']
            return remove_english_artifacts(content)
        except Exception as e:
            time.sleep(1)
    return ""

def main():
    if not os.path.exists(INPUT_FILE):
        print("File not found.")
        return

    # تحميل الموديل تلقائياً إذا لم يكن موجوداً
    print(f"🚀 Pulling model {MODEL_NAME} (Size: ~1.6 GB)...")
    try:
        ollama.pull(MODEL_NAME)
    except:
        pass

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"⚡ Processing {len(chunks)} chunks with {MODEL_NAME}...")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        result = translate_segment(chunk)
        if result:
            with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
                f.write(result + "\n\n")

    print(f"✅ Done! Saved to: {OUTPUT_FILE}")

    # عرض عينة
    if os.path.exists(OUTPUT_FILE):
        print("-" * 30)
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
        print("-" * 30)

if __name__ == "__main__":
    main()

"""gemmaa2 baaaaaaaaaaaaaaaaaaad"""









import ollama
import os
import re
import time
from tqdm.notebook import tqdm

# ------------------- Settings -------------------
INPUT_FILE = "text.txt"
OUTPUT_FILE = "dracula_final.txt"

# سنعود لـ Phi-3 Medium لأنه أفضل توازن بين الذكاء والسرعة للنصوص الأدبية
# النماذج الصغيرة (2B) تفشل في الروايات وتكرر الكلام
MODEL_NAME = "phi3:medium"

CHUNK_SIZE = 1000

# ------------------- SYSTEM PROMPT -------------------
SYSTEM_PROMPT = (
    "ROLE: Expert Arabic Translator for Novels.\n"
    "TASK: Translate the English text to Arabic.\n"
    "RULES:\n"
    "1. NO REPETITION: Never repeat sentences. If you get stuck, move to the next sentence.\n"
    "2. TRANSLITERATE: 'Munich' -> 'ميونخ', 'Dracula' -> 'دراكولا'.\n"
    "3. SCRIPT: Arabic only. No English/Japanese characters.\n"
    "4. STYLE: Narrative and descriptive."
)

def remove_garbage(text):
    """حذف التكرار والأسطر الغريبة"""
    lines = text.split('\n')
    cleaned = []
    seen = set()
    for line in lines:
        line = line.strip()
        # حذف السطر إذا كان تكراراً لسطر سابق
        if line in seen:
            continue
        # حذف الأسطر التي تحتوي تشكيل مبالغ فيه (علامة الهلوسة)
        if len(re.findall(r'[\u064B-\u065F]', line)) > len(line) * 0.4:
            continue

        if line:
            seen.add(line)
            cleaned.append(line)
    return '\n'.join(cleaned)

def split_text_smart(text, max_length):
    chunks = []
    while len(text) > max_length:
        split_index = text.rfind('\n', 0, max_length)
        if split_index == -1: split_index = text.rfind('.', 0, max_length)
        if split_index == -1: split_index = max_length
        chunks.append(text[:split_index + 1])
        text = text[split_index + 1:].strip()
    if text: chunks.append(text)
    return chunks

def translate_segment(text_chunk, retries=3):
    for attempt in range(retries):
        try:
            response = ollama.chat(
                model=MODEL_NAME,
                messages=[
                    {'role': 'system', 'content': SYSTEM_PROMPT},
                    {'role': 'user', 'content': text_chunk},
                ],
                options={
                    'temperature': 0.4,     # حرارة متوسطة للإبداع بدون جنون
                    'repeat_penalty': 1.3,  # هام جداً: يمنع تكرار الجمل (الحل لمشكلتك)
                    'top_k': 50,            # تنويع الكلمات
                    'num_predict': 1500,
                }
            )
            content = response['message']['content']
            return remove_garbage(content)
        except Exception as e:
            print(f"Error: {e}")
            time.sleep(1)
    return "[Translation Failed]"

def main():
    if not os.path.exists(INPUT_FILE):
        print("File not found.")
        return

    print(f"🚀 Pulling {MODEL_NAME}...")
    try:
        ollama.pull(MODEL_NAME)
    except:
        pass

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        full_text = f.read()

    chunks = split_text_smart(full_text, CHUNK_SIZE)
    print(f"⚡ Translating {len(chunks)} parts...")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("")

    for chunk in tqdm(chunks, desc="Translating"):
        result = translate_segment(chunk)
        with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
            f.write(result + "\n\n")

    print(f"✅ Done! Check {OUTPUT_FILE}")

    if os.path.exists(OUTPUT_FILE):
        print("-" * 30)
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            print(f.read()[:500] + "...")
        print("-" * 30)

if __name__ == "__main__":
    main()